server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservicios
    username: postgres
    password: academyjava
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085